version: "2"
services:
  requisition-ui:
    image: openlmis/dev-ui:1
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
  image:
    build: .
    image: openlmis/requisition-ui