version: "2"
services:
  requisition-ui:
    image: openlmis/dev-ui:5
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - ui-components
      - ui-layout
      - stockmanagement-ui
    depends_on:
      - auth-ui
      - referencedata-ui
      - ui-components
      - ui-layout
      - stockmanagement-ui
  auth-ui:
    image: openlmis/auth-ui:5.0.4-SNAPSHOT
    volumes:
      - '/openlmis-auth-ui'
  fulfillment-ui:
    image: openlmis/fulfillment-ui:5.0.4-SNAPSHOT
    volumes:
      - '/openlmis-fulfillment-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.2.2-SNAPSHOT
    volumes:
      - '/openlmis-referencedata-ui'
  ui-components:
    image: openlmis/ui-components:5.2.0-SNAPSHOT
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.0.3-SNAPSHOT
    volumes:
      - '/openlmis-ui-layout'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:1.0.1-SNAPSHOT
    volumes:
     - '/openlmis-stockmanagement-ui'
  image:
    build: .
    image: openlmis/requisition-ui
