version: "2"
services:
  requisition-refui:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: openlmis/requisition-refui-dev
    ports:
      - "9000:9000"
    volumes:
      - '.:/app'